name: Feelo
options:
  bundleIdPrefix: com.riyanfirdausamerta
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

targets:
  Feelo:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Feelo
        excludes:
          - "**/.DS_Store"
    info:
      path: Feelo/Info.plist
      properties:
        CFBundleDisplayName: Feelo
        NSCameraUsageDescription: "Camera is used to track your body movements for the game."
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: YES
    dependencies:
      - sdk: AVFoundation.framework
      - sdk: Vision.framework
      - sdk: WebKit.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.riyanfirdausamerta.feelo
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MACCATALYST: NO
